GET http://localhost:5000/api/users/

###

GET http://localhost:5000/api/users/AksHay

###

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "username": "Yashwanth",
    "password": "yash123",
    "email": "yashwanth@gmail.com",
    "role": "HR",
    "location": "Hyderabad",
    "hiringCtc": 10,
    "industry": "IT"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json
    
{
    "username": "akshay",
    "password": "akshay123"
}

###

GET http://localhost:5000/api/users/all/account-managers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

GET http://localhost:5000/api/users/all/hr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

POST http://localhost:5000/jobs/add/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

// companyName, title, category, description, location, ctc, skills, employmentType, workType, commission, noOfOpenings, status, hiringNeed, postedBy, assignedTo

{
    "companyName": "Google",
    "title": "Software Engineer",
    "category": "IT",
    "description": "Software Engineer",
    "location": "Bangalore",
    "ctc": 10,
    "skills": "Java, Python, C++",
    "employmentType": "Full Time",
    "workType": "Work From Home",
    "commission": "10%",
    "noOfOpenings": 10,
    "status": "Open",
    "hiringNeed": "Urgent",
    "postedBy": "Prashobh",
    "assignedTo": "Akshay"
}

###

POST http://localhost:5000/jobs/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

//jobId, assignedTo, assignedBy
    
{
    "jobId": "38993740-f3d8-4749-871f-9dab5dfafce7",
    "assignedTo": "Akshay",
    "assignedBy": "Prashobh"
}

###

GET http://localhost:5000/jobs/account-manager/Akshay
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

GET http://localhost:5000/jobs/hr/akshay
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

POST http://localhost:5000/jobs/candidate/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

// candidateName, candidateEmail, candidatePhone, jobId, username, offerStatus

{
    "candidateName": "santhosh",
    "candidateEmail": "santhosh123@gmail.com",
    "candidatePhone": "9874563210",
    "jobId": "38993740-f3d8-4749-871f-9dab5dfafce7",
    "username": "Akshay",
    "offerStatus": "Pending"
}

###

GET http://localhost:5000/jobs/candidate/38993740-f3d8-4749-871f-9dab5dfafce7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

PUT http://localhost:5000/jobs/candidate/status/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY


//candidateId, jobId, username, offerStatus
{
    "candidateId": "d51e4560-5ad3-4025-9878-f4b6b48e80a3",
    "jobId": "38993740-f3d8-4749-871f-9dab5dfafce7",
    "username": "Akshay",
    "offerStatus": "Selected"
}